apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: jsisques/dashboard:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---

