apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: frontend
spec:
  type: NodePort
  selector:
    app: dashboard
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000
