name: Crear y subir a el contenedor de docker a DockerHub

on:
  push:
    branches: ['dev', 'main']
  pull_request:
    branches: ['dev', 'main']

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  REPOSITORY_NAME: Frontend-Dashboard
  USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  push_to_registry:
    name: Subir el contenedor al DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Realizar un checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Iniciar sesión en DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extraer los metadatos (tags, labels) para Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.REPOSITORY_NAME }}

      - name: Construir y subir la imagen de Docker
        uses: docker/build-push-action@v2
        with:
          context: '{{defaultContext}}'
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
